### PR TITLE
🐛 FIX: install, slash directory, build, clean

### PR DESCRIPTION
**Pull request by ahmedrowaihi**

### CODE REVIEW

**Comment by ahmedrowaihi** [comment]
Hmmm, I think I could rewrite it in better syntax, this ${DIRECTORY_SEPERTOR} is too verbose..

**Comment by yazeed1s** [comment]
Yeah, you could use '${DIR}' or '${SLASH}' instead.

**Comment by ahmedrowaihi** [comment]
@Yazeed1s 
I rewrote all with ```ifeq/else```, I think it's much readable and maintainable this way, rather than ${DIR} between DIRs

if you have any concerns, let me know :'D

**Review by yazeed1s — APPROVED** [review]
cool, thanks for making this Windows compatible!

**Pull request merged**
